name: 'Auto Assign'
on:
  pull_request:
    types: [ opened ]
    branches: [ master ]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/workflows/config/auto_assign.yml"
